# Generated by Django 4.0.4 on 2022-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='esg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.CharField(blank=True, max_length=1000, null=True)),
                ('background_image', models.ImageField(upload_to='uploads/')),
                ('service1_headline', models.CharField(blank=True, max_length=50, null=True)),
                ('service1_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('service1_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('service2_headline', models.CharField(blank=True, max_length=50, null=True)),
                ('service2_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('service2_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('service3_headline', models.CharField(blank=True, max_length=50, null=True)),
                ('service3_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('service3_text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
