# Generated by Django 4.0.4 on 2022-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('pic', models.ImageField(upload_to='team/')),
                ('linkedin', models.URLField(blank=True, max_length=2000, null=True)),
                ('bio', models.CharField(blank=True, max_length=5000, null=True)),
                ('languages', models.CharField(blank=True, max_length=2000, null=True)),
                ('since', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='esg',
            new_name='service',
        ),
    ]
