# Generated by Django 4.0.4 on 2022-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_rename_esg_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
