# Generated by Django 4.0.4 on 2022-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_about_headline_alter_home_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
