# Generated by Django 4.0.4 on 2022-06-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_service_service_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='values',
            new_name='value',
        ),
    ]
