# Generated by Django 4.0.4 on 2022-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_values_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(choices=[('ESG', 'ESG'), ('Integrity', 'Integrity'), ('Investigations', 'Investigations')], db_index=True, default='ESG', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
